FROM node:22-alpine AS builder

WORKDIR /app

COPY frontend/package*.json /app/
RUN npm install

COPY frontend /app

RUN npm run build

FROM nginx:1.27-alpine

COPY --from=builder /app/dist /usr/share/nginx/html